<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyTitle>Necrofancy.PrepareProcedurally.HumanoidAlienRaces</AssemblyTitle>
        <OutputPath>..\..\Release\$(RimWorldVersion)\HAR\Assemblies\</OutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Necrofancy.PrepareProcedurally\Necrofancy.PrepareProcedurally.csproj">
            <Properties>RimWorldVersion=$(RimWorldVersion)</Properties>
        </ProjectReference>
    </ItemGroup>

    <ItemGroup>
        <Reference Include="Assembly-CSharp">
            <HintPath>..\..\Steam\$(RimWorldVersion)\Game\Assembly-CSharp.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="UnityEngine.CoreModule">
            <HintPath>..\..\Steam\$(RimWorldVersion)\Game\UnityEngine.CoreModule.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="AlienRace">
            <HintPath>..\..\Steam\$(RimWorldVersion)\AlienRace\AlienRace.dll</HintPath>
            <Private>false</Private>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="bin\**;obj\**" />
        <None Remove="bin\**;obj\**" />
    </ItemGroup>
</Project>