<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <LangVersion>latest</LangVersion>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>

        <!-- Default to 1.6 if no version is specified -->
        <RimWorldVersion Condition="'$(RimWorldVersion)' == ''">1.6</RimWorldVersion>

        <!-- Output folder specific to HAR patches -->
        <OutputPath>..\..\Release\$(RimWorldVersion)\HAR\Assemblies\</OutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>

        <!-- Define a constant for version-specific code -->
        <DefineConstants>$(DefineConstants);RW$(RimWorldVersion.Replace('.', '_'))</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="All" />
        <PackageReference Include="Lib.Harmony" Version="2.4.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Necrofancy.PrepareProcedurally\Necrofancy.PrepareProcedurally.csproj">
            <Properties>RimWorldVersion=$(RimWorldVersion)</Properties>
        </ProjectReference>
    </ItemGroup>

    <ItemGroup>
        <Reference Include="Assembly-CSharp">
            <HintPath>..\..\Steam\$(RimWorldVersion)\Game\Assembly-CSharp.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="UnityEngine.CoreModule">
            <HintPath>..\..\Steam\$(RimWorldVersion)\Game\UnityEngine.CoreModule.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="AlienRace">
            <HintPath>..\..\Steam\$(RimWorldVersion)\AlienRace\AlienRace.dll</HintPath>
            <Private>false</Private>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="bin\**;obj\**" />
        <None Remove="bin\**;obj\**" />
    </ItemGroup>
</Project>